assets:     
  - db.sql.gz
steps:
  - name: Download Drupal 7
    plugin: Shell
    command: "drush dl drupal-7.x --destination=/var/www"
  - name: Rename web dir
    plugin: Shell
    command: "mv /var/www/drupal-7.x-dev /var/www/html"
  - name: Probo CI site setup
    plugin: Drupal
    database: db.sql.gz
    databaseGzipped: true
    databaseUpdates: true
    clearCaches: true
  - name: Make Module Dirs
    plugin: Shell
    command: "mkdir /var/www/html/sites/all/modules/stanford && mkdir /var/www/html/sites/all/modules/stanford/stanford_bean_types"
  - name: Move module source to stanford dir
    command: "mv /src/* /var/www/html/sites/all/modules/stanford/stanford_bean_types/"
  - name: Set file directory permissions
    plugin: Shell
    command: 'chown -R www-data:www-data /var/www/html/sites/default/files'
  - name: Dl and enable features
    plugin: Shell
    command: "drush --root=/var/www/html dl features -y && drush --root=/var/www/html en features"
  - name: Clone stanford dependencies
    command: "git clone https://github.com/SU-SWS/stanford_image.git /var/www/html/sites/all/modules/stanford/stanford_image && git clone https://github.com/SU-SWS/stanford_image_styles.git /var/www/html/sites/all/modules/stanford/stanford_image_styles"
  - name: Dependencies Prefetch
    command: "drush -root/var/www/html dl ds bean -y"
  - name: Dependencies Prefech enable
    command: "drush --root=/var/www/html en bean_admin_ui ds_extras -y"
  - name: Enable and download dependencies
    plugin: Shell
    command: "drush --root=/var/www/html en stanford_bean_types -y"
  - name: Revert all features
    plugin: Shell
    command: 'drush --root="/var/www/html" fra -y'
  - name: Update all the things
    plugin: Shell
    command: 'drush --root="/var/www/html" updb -y'
  - name: Clear cache
    plugin: Shell
    command: 'drush --root="/var/www/html" cc all -y'
